// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:texnomart_clone/data/models/cart/cart_model.dart';
import 'package:texnomart_clone/data/models/product/product_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CartModelAdapter());
    registerAdapter(ProductAdapter());
  }
}
